### ISSUE TITLE
missing package for ansible

### ISSUE THREAD

**Issue by lukasruoff** [meengit/vagrant-ansible-windows#4]
wcwidth is missing

**Comment by meengit** [comment]
@lukasruoff, thank you very much for reporting this. After some investigation, [I updated the guide](https://github.com/meengit/vagrant-ansible-windows/commit/376b4b468cc94bff0ffea673e846eb9aea6239ea#diff-1550ec65ac92f65817fc28928dfef526912b5f52356ff43651369bae92f56031R95-R98) to also address wcwidth
